# fly.toml app configuration file generated for raylib-web on 2023-11-01T21:36:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "raylib-web"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
